import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import average_precision_score, precision_recall_curve
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import os
import logging
from typing import Tuple, Dict, Any
import re

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Constants
ASSETS_DIR = 'assets'
MODELS_DIR = 'models'
README_PATH = 'README.md'
DATA_PATH = os.path.join('data', 'raw_transactions.csv')

def setup_directories():
    os.makedirs(ASSETS_DIR, exist_ok=True)
    os.makedirs(MODELS_DIR, exist_ok=True)

def load_and_preprocess_data(file_path: str) -> Tuple[pd.DataFrame, pd.Series]:
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Data file not found at {file_path}. Run data_generator.py first.")
    
    logger.info(f"Loading data from {file_path}")
    df = pd.read_csv(file_path)
    
    # Drop identifiers and timestamp
    drop_cols = ['transaction_id', 'sender_account_id', 'receiver_account_id', 'timestamp', 'is_fraud']
    drop_cols = [col for col in drop_cols if col in df.columns]
    
    X = df.drop(columns=drop_cols)
    y = df['is_fraud']
    
    # Fill any NaNs generated by rolling/diff functions
    X = X.fillna(0)
    
    logger.info(f"Features used: {list(X.columns)}")
    return X, y

def train_model(X_train: pd.DataFrame, y_train: pd.Series) -> xgb.XGBClassifier:
    logger.info("Training XGBoost with cost-sensitive learning...")
    neg_cases = (y_train == 0).sum()
    pos_cases = (y_train == 1).sum()
    scale_pos_weight = neg_cases / max(1, pos_cases)
    
    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.05,
        scale_pos_weight=scale_pos_weight,
        eval_metric='logloss',
        random_state=42
    )
    model.fit(X_train, y_train)
    return model

def evaluate_and_plot(model: xgb.XGBClassifier, X_test: pd.DataFrame, y_test: pd.Series) -> Dict[str, Any]:
    logger.info("Evaluating Model...")
    y_prob = model.predict_proba(X_test)[:, 1]
    
    # 1. Calculate PR-AUC
    pr_auc = average_precision_score(y_test, y_prob)
    logger.info(f"PR-AUC: {pr_auc:.4f}")
    
    # Calculate Business Metric (Total GBP Saved on Test Set)
    # Re-attach amount_gbp to test set for calculation
    # We define "Saved" as True Positives * Amount
    fraud_threshold = 0.80
    y_pred = (y_prob >= fraud_threshold).astype(int)
    
    true_positives_mask = (y_test == 1) & (y_pred == 1)
    
    # Safe extraction of amount_gbp (assuming it's a feature)
    if 'amount_gbp' in X_test.columns:
        gbp_saved = X_test.loc[true_positives_mask, 'amount_gbp'].sum()
    else:
        gbp_saved = 0.0
        
    logger.info(f"Total GBP Saved on Test Set: £{gbp_saved:,.2f}")

    sns.set_theme(style="whitegrid")
    
    # 2. Plot Precision-Recall Curve (Matplotlib/Seaborn)
    precision, recall, _ = precision_recall_curve(y_test, y_prob)
    
    plt.figure(figsize=(8, 6))
    plt.plot(recall, precision, color='darkorange', lw=2, label=f'PR curve (AUC = {pr_auc:.3f})')
    plt.xlabel('Recall (Fraud Caught)')
    plt.ylabel('Precision (Accuracy of Blocks)')
    plt.title('Precision-Recall Curve for APP Fraud')
    plt.legend(loc="lower left")
    
    pr_curve_path = os.path.join(ASSETS_DIR, 'pr_curve.png')
    plt.savefig(pr_curve_path, bbox_inches='tight', dpi=300)
    plt.close()
    logger.info(f"Saved PR Curve to {pr_curve_path}")
    
    # 3. Plot SHAP Summary Plot
    logger.info("Generating SHAP Explanations...")
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_test)
    
    plt.figure(figsize=(10, 8))
    # Note: shap.summary_plot calls plt.show() internally in some versions, 
    # so we must pass show=False to save it programmatically
    shap.summary_plot(shap_values, X_test, show=False)
    
    shap_summary_path = os.path.join(ASSETS_DIR, 'shap_summary.png')
    plt.savefig(shap_summary_path, bbox_inches='tight', dpi=300)
    plt.close()
    logger.info(f"Saved SHAP Summary Plot to {shap_summary_path}")
    
    return {
        "pr_auc": pr_auc,
        "gbp_saved": gbp_saved,
        "pr_curve_path": "assets/pr_curve.png",
        "shap_summary_path": "assets/shap_summary.png"
    }

def update_readme(metrics: Dict[str, Any]):
    """Programmatically append or replace the Model Performance Results section in README.md."""
    if not os.path.exists(README_PATH):
        logger.warning(f"{README_PATH} not found. Skipping documentation update.")
        return
        
    logger.info(f"Updating {README_PATH} with latest metrics...")
    
    with open(README_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    # The markdown section to inject
    new_section = f"""
## 📈 Model Performance Results

Our cost-sensitive XGBoost pipeline automatically evaluates itself upon training to ensure production readiness against highly imbalanced fraud typologies.

*   **Precision-Recall AUC:** `{metrics['pr_auc']:.4f}`
*   **Total Expected GBP Saved (Test Set):** `£{metrics['gbp_saved']:,.2f}`

### Precision-Recall Analysis
The PR-AUC is the gold standard for heavily imbalanced datasets like APP fraud, indicating the trade-off between accurately identifying fraud (Recall) and minimizing customer friction from false positives (Precision).

![Precision-Recall Curve]({metrics['pr_curve_path']})

### Explainable AI (SHAP) Compliance
To comply with FCA/PSR regulations regarding algorithmic transparency, we extract SHapley Additive exPlanations feature importances globally. This proves to stakeholders *which* engineered velocity and network features are driving model decisions.

![SHAP Summary Plot]({metrics['shap_summary_path']})
"""

    # Look for existing section to replace, else append
    section_header_pattern = r"## 📈 Model Performance Results.*?(?=## |\Z)"
    
    # re.DOTALL allows the dot to match newlines
    if re.search(section_header_pattern, content, flags=re.DOTALL | re.IGNORECASE):
        # Replace existing
        updated_content = re.sub(section_header_pattern, new_section.strip() + "\n\n", content, flags=re.DOTALL | re.IGNORECASE)
        logger.info("Replaced existing performance section in README.")
    else:
        # Append to the end
        updated_content = content.strip() + "\n\n" + new_section.strip() + "\n"
        logger.info("Appended new performance section to README.")

    with open(README_PATH, 'w', encoding='utf-8') as f:
        f.write(updated_content)

def main():
    try:
        setup_directories()
        
        X, y = load_and_preprocess_data(DATA_PATH)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
        
        model = train_model(X_train, y_train)
        
        # Save Model
        model_path = os.path.join(MODELS_DIR, 'xgb_fraud_model.json')
        model.save_model(model_path)
        logger.info(f"Model saved to {model_path}")
        
        # Evaluate & Generate Assets
        metrics = evaluate_and_plot(model, X_test, y_test)
        
        # The Magic Step: Automated Documentation
        update_readme(metrics)
        
        logger.info("Pipeline completed successfully!")
        
    except Exception as e:
        logger.error(f"Error in training pipeline: {str(e)}")
        raise

if __name__ == '__main__':
    main()
